/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ViewLayer;
import BussinesModelLayer.Producto;
import BussinesModelLayer.Farmacia;
import BussinesModelLayer.Metodos;
import javax.swing.JOptionPane;
/**
 *
 * @author zerme
 */
public class PrincipalFarma extends javax.swing.JFrame {
    
    //Variables globales
    Metodos metodo = new Metodos();
    Farmacia farmacia = new Farmacia();
    Producto producto = new Producto();
    int relacion;
    
    /**
     * Creates new form Principal
     */
    public PrincipalFarma() {
        initComponents();
        farmacia.farmaciasExiste();
        producto.productosExiste();
        farmacia.mostrarDatos(tblFarmacia);
        if (DataAccessLayer.DataAccess.leerCSV("Farmacias.csv").size()>1) {
            producto.mostrarDatos(tblProducto, Integer.parseInt(DataAccessLayer.DataAccess.leerCSV("Farmacias.csv").get(1)[0]));
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        pnlProducto = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProducto = new javax.swing.JTable();
        labelProducto = new javax.swing.JLabel();
        btnRegistrarProd = new javax.swing.JButton();
        labelCaducidad = new javax.swing.JLabel();
        txtCaducidad = new javax.swing.JTextField();
        txtNombreProd = new javax.swing.JTextField();
        labelName1 = new javax.swing.JLabel();
        labelInventario = new javax.swing.JLabel();
        txtInventario = new javax.swing.JTextField();
        txtBuscadorProducto = new javax.swing.JTextField();
        btnBuscarP = new javax.swing.JButton();
        btnActualizarP = new javax.swing.JButton();
        btnGraficar = new javax.swing.JButton();
        pnlFarmacia = new javax.swing.JPanel();
        labelName = new javax.swing.JLabel();
        labelDireccion = new javax.swing.JLabel();
        labelTelefono = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtNombreFar = new javax.swing.JTextField();
        labelFarmacia = new javax.swing.JLabel();
        btnRegistrarFar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblFarmacia = new javax.swing.JTable();
        txtBuscadorFarmacia = new javax.swing.JTextField();
        btnBuscarF = new javax.swing.JButton();
        btnActualizarF = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);

        tblProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Producto", "ID Farmacia", "Nombre", "Caducidad", "Inventario"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblProducto.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblProducto);
        if (tblProducto.getColumnModel().getColumnCount() > 0) {
            tblProducto.getColumnModel().getColumn(0).setResizable(false);
            tblProducto.getColumnModel().getColumn(1).setResizable(false);
            tblProducto.getColumnModel().getColumn(2).setResizable(false);
            tblProducto.getColumnModel().getColumn(3).setResizable(false);
            tblProducto.getColumnModel().getColumn(4).setResizable(false);
        }

        labelProducto.setText("Productos");

        btnRegistrarProd.setText("Registrar");
        btnRegistrarProd.setEnabled(false);
        btnRegistrarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarProdActionPerformed(evt);
            }
        });

        labelCaducidad.setText("Caducidad:");

        txtCaducidad.setEnabled(false);

        txtNombreProd.setEnabled(false);

        labelName1.setText("Nombre:");

        labelInventario.setText("Inventario:");

        txtInventario.setEnabled(false);
        txtInventario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtInventarioKeyTyped(evt);
            }
        });

        txtBuscadorProducto.setEditable(false);
        txtBuscadorProducto.setToolTipText("");
        txtBuscadorProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtBuscadorProducto.setName("");

        btnBuscarP.setText("Buscar");
        btnBuscarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPActionPerformed(evt);
            }
        });

        btnActualizarP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/reload.png"))); // NOI18N
        btnActualizarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarPActionPerformed(evt);
            }
        });

        btnGraficar.setText("Graficar Inventario");
        btnGraficar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGraficarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlProductoLayout = new javax.swing.GroupLayout(pnlProducto);
        pnlProducto.setLayout(pnlProductoLayout);
        pnlProductoLayout.setHorizontalGroup(
            pnlProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlProductoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnRegistrarProd)
                .addGap(75, 75, 75))
            .addGroup(pnlProductoLayout.createSequentialGroup()
                .addGroup(pnlProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlProductoLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(pnlProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlProductoLayout.createSequentialGroup()
                                .addGroup(pnlProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlProductoLayout.createSequentialGroup()
                                        .addGap(82, 82, 82)
                                        .addComponent(txtBuscadorProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnlProductoLayout.createSequentialGroup()
                                        .addComponent(btnActualizarP)
                                        .addGap(271, 271, 271)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscarP))))
                    .addGroup(pnlProductoLayout.createSequentialGroup()
                        .addGap(320, 320, 320)
                        .addComponent(labelProducto)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelCaducidad)
                    .addComponent(labelName1)
                    .addComponent(labelInventario))
                .addGap(18, 18, 18)
                .addGroup(pnlProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtCaducidad)
                        .addComponent(txtInventario)
                        .addComponent(txtNombreProd, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
                    .addComponent(btnGraficar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlProductoLayout.setVerticalGroup(
            pnlProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlProductoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelProducto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlProductoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(pnlProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlProductoLayout.createSequentialGroup()
                                .addComponent(btnActualizarP)
                                .addGap(6, 6, 6))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlProductoLayout.createSequentialGroup()
                                .addComponent(txtBuscadorProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))))
                    .addGroup(pnlProductoLayout.createSequentialGroup()
                        .addGroup(pnlProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnBuscarP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnGraficar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(pnlProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlProductoLayout.createSequentialGroup()
                        .addGroup(pnlProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelName1)
                            .addComponent(txtNombreProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelCaducidad)
                            .addComponent(txtCaducidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelInventario)
                            .addComponent(txtInventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRegistrarProd)
                .addGap(12, 12, 12))
        );

        labelName.setText("Nombre:");

        labelDireccion.setText("Dirección:");

        labelTelefono.setText("Teléfono:");

        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyTyped(evt);
            }
        });

        labelFarmacia.setText("Farmacia");

        btnRegistrarFar.setText("Registrar");
        btnRegistrarFar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarFarActionPerformed(evt);
            }
        });

        tblFarmacia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Farmacia", "Nombre", "Dirección", "Teléfono"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblFarmacia.getTableHeader().setReorderingAllowed(false);
        tblFarmacia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblFarmaciaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblFarmacia);
        if (tblFarmacia.getColumnModel().getColumnCount() > 0) {
            tblFarmacia.getColumnModel().getColumn(0).setResizable(false);
            tblFarmacia.getColumnModel().getColumn(1).setResizable(false);
            tblFarmacia.getColumnModel().getColumn(2).setResizable(false);
            tblFarmacia.getColumnModel().getColumn(3).setResizable(false);
        }

        btnBuscarF.setText("Buscar");
        btnBuscarF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarFActionPerformed(evt);
            }
        });

        btnActualizarF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/reload.png"))); // NOI18N
        btnActualizarF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlFarmaciaLayout = new javax.swing.GroupLayout(pnlFarmacia);
        pnlFarmacia.setLayout(pnlFarmaciaLayout);
        pnlFarmaciaLayout.setHorizontalGroup(
            pnlFarmaciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFarmaciaLayout.createSequentialGroup()
                .addGroup(pnlFarmaciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFarmaciaLayout.createSequentialGroup()
                        .addGroup(pnlFarmaciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlFarmaciaLayout.createSequentialGroup()
                                .addGap(83, 83, 83)
                                .addComponent(btnRegistrarFar))
                            .addGroup(pnlFarmaciaLayout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(pnlFarmaciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelDireccion)
                                    .addComponent(labelName)
                                    .addComponent(labelTelefono))
                                .addGap(18, 18, 18)
                                .addGroup(pnlFarmaciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtDireccion)
                                    .addComponent(txtTelefono)
                                    .addComponent(txtNombreFar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(pnlFarmaciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlFarmaciaLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(btnActualizarF)
                                .addGap(55, 55, 55)
                                .addComponent(txtBuscadorFarmacia, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnBuscarF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlFarmaciaLayout.createSequentialGroup()
                        .addGap(330, 330, 330)
                        .addComponent(labelFarmacia)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        pnlFarmaciaLayout.setVerticalGroup(
            pnlFarmaciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFarmaciaLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(labelFarmacia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlFarmaciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFarmaciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelName)
                        .addComponent(txtNombreFar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnActualizarF, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFarmaciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtBuscadorFarmacia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBuscarF)))
                .addGap(20, 20, 20)
                .addGroup(pnlFarmaciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFarmaciaLayout.createSequentialGroup()
                        .addGroup(pnlFarmaciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelDireccion)
                            .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlFarmaciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelTelefono)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addComponent(btnRegistrarFar))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlFarmacia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(pnlFarmacia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarFarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarFarActionPerformed
        
        if(!(txtNombreFar.getText().equals("")
                &&txtDireccion.getText().equals("")
                &&txtTelefono.getText().equals(""))){
            
            farmacia = new Farmacia(farmacia.sacarID(), txtNombreFar.getText(), 
                    txtDireccion.getText(), txtTelefono.getText());
            
            metodo.guardarRegistro("Farmacias.csv", farmacia.aString());
            farmacia.mostrarDatos(tblFarmacia);
            txtNombreFar.setText("");
            txtDireccion.setText("");
            txtTelefono.setText("");
        }     
    }//GEN-LAST:event_btnRegistrarFarActionPerformed

    private void tblFarmaciaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblFarmaciaMouseClicked
        producto.mostrarDatos(tblProducto, Integer.parseInt((String) tblFarmacia.getValueAt(tblFarmacia.getSelectedRow(), 0)));
        txtBuscadorProducto.setEditable(true);
        txtNombreProd.setEnabled(true);
        txtCaducidad.setEnabled(true);
        txtInventario.setEnabled(true);
        btnRegistrarProd.setEnabled(true);
    }//GEN-LAST:event_tblFarmaciaMouseClicked

    private void btnRegistrarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarProdActionPerformed
        
        if(!(txtNombreProd.getText().equals("")
                &&txtCaducidad.getText().equals("")
                &&txtInventario.getText().equals(""))){
            
            relacion = Integer.parseInt((String) tblFarmacia.getValueAt(tblFarmacia.getSelectedRow(), 0));
            producto = new Producto(producto.sacarID(),Integer.parseInt(txtInventario.getText()), 
                    txtNombreProd.getText(), txtCaducidad.getText(), relacion);
            
            metodo.guardarRegistro("Productos.csv", producto.aString());
            producto.mostrarDatos(tblProducto, relacion);
            
            txtNombreProd.setText("");
            txtCaducidad.setText("");
            txtInventario.setText("");
        }
    }//GEN-LAST:event_btnRegistrarProdActionPerformed

    private void txtInventarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInventarioKeyTyped
        metodo.esNumero(evt);
    }//GEN-LAST:event_txtInventarioKeyTyped

    private void txtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyTyped
        metodo.esNumero(evt);
    }//GEN-LAST:event_txtTelefonoKeyTyped

    private void btnBuscarFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarFActionPerformed
        farmacia.buscarPorNombre(txtBuscadorFarmacia.getText(), tblFarmacia);
    }//GEN-LAST:event_btnBuscarFActionPerformed

    private void btnBuscarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPActionPerformed
        if (tblFarmacia.getSelectedRow()==-1) {
            JOptionPane.showMessageDialog(null, "Seleccione una farmacia para buscar");
        }else{
            producto.buscarPorNombre(txtBuscadorProducto.getText(), tblProducto, 
                    Integer.parseInt((String) tblFarmacia.getValueAt(tblFarmacia.getSelectedRow(), 0)));
        }
    }//GEN-LAST:event_btnBuscarPActionPerformed

    private void btnActualizarFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarFActionPerformed
        farmacia.mostrarDatos(tblFarmacia);
    }//GEN-LAST:event_btnActualizarFActionPerformed

    private void btnActualizarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarPActionPerformed
        if (tblFarmacia.getSelectedRow()==-1) {
            JOptionPane.showMessageDialog(null, "Seleccione una farmacia para buscar");
        }else{
            producto.mostrarDatos(tblProducto, tblFarmacia.getSelectedRow());
        }
    }//GEN-LAST:event_btnActualizarPActionPerformed

    private void btnGraficarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGraficarActionPerformed
        metodo.graficarInventario();
    }//GEN-LAST:event_btnGraficarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalFarma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarF;
    private javax.swing.JButton btnActualizarP;
    private javax.swing.JButton btnBuscarF;
    private javax.swing.JButton btnBuscarP;
    private javax.swing.JButton btnGraficar;
    private javax.swing.JButton btnRegistrarFar;
    private javax.swing.JButton btnRegistrarProd;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelCaducidad;
    private javax.swing.JLabel labelDireccion;
    private javax.swing.JLabel labelFarmacia;
    private javax.swing.JLabel labelInventario;
    private javax.swing.JLabel labelName;
    private javax.swing.JLabel labelName1;
    private javax.swing.JLabel labelProducto;
    private javax.swing.JLabel labelTelefono;
    private javax.swing.JPanel pnlFarmacia;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JPanel pnlProducto;
    private javax.swing.JTable tblFarmacia;
    private javax.swing.JTable tblProducto;
    private javax.swing.JTextField txtBuscadorFarmacia;
    private javax.swing.JTextField txtBuscadorProducto;
    private javax.swing.JTextField txtCaducidad;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtInventario;
    private javax.swing.JTextField txtNombreFar;
    private javax.swing.JTextField txtNombreProd;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables

    
}
